### ISSUE TITLE
Unable to configure plugin when installed from repository

### ISSUE THREAD

**Issue by Dysta** [hexxone/TeleJelly#1]
Hello, I just discovered this plugin and wanna give a try. I followed the installation guide in the readme and added the repository.

Now, step two tell me to open configuration from the plugin but the plugin show a "NotSupported" state and I'm unable to open the settings.
![image](https://github.com/hexxone/TeleJelly/assets/25008828/199c5885-982f-4e26-a25d-ebfb6060fdc8)
No configuration detected
![image](https://github.com/hexxone/TeleJelly/assets/25008828/dbcc2ff5-8c18-437d-9836-49034048ff95)

plugin version: 1.0.4
jellyfin version: 10.8.13

**Comment by hexxone** [comment]
Hi, I'm sorry but I'm working on it in this exact moment :)
It should be fixxed within an hour max.

**Comment by Dysta** [comment]
Thank you for fast reply, I'm waiting then 😄

**Comment by hexxone** [comment]
Hey there, it took longer than I thought but it should finally be working 👍 (Version 1.0.6)
Let me know again if it doesn't
