### ISSUE TITLE
Plugin doesnt work for Jellyfin Version 10.9

### ISSUE THREAD

**Issue by RevolDark** [hexxone/TeleJelly#2]
Hello :)

Thank you for taking the time for this project.

I can't log in although if they pass the data, it ends up giving an error in a line of code, I think it refers to a code that no longer works, (probably due to the new version of jellyfin 10.9.7)

![image](https://github.com/user-attachments/assets/c2bb3c8d-4124-4806-92b3-f7215cbd7d07)

 - Jellyfin OS:  Linux and Docker
 - Jellyfin Version:  10.9.7
 - Plugin Version: 1.0.7

It's too much to ask if you can prepare a hotfix for the new version that works? it would be great.

Thanks.

**Comment by hexxone** [comment]
Hi,

Thank you for your interest in the plugin.

Unfortunately I am currently on vacation.

I will try to get it fixed when back.

Until then, if you really need the Plugin I would recommend downgrading Jellyfin to version 10.8 :)

Greetings

**Comment by RevolDark** [comment]
oh, Enjoy the holidays. 

If the problem is that clients update to the latest versions and do not allow it to be used :( 

I hope you return from vacation, thank you very much !

**Comment by Borgsareus** [comment]
Hi there, 

I'm having the same issue. I'm currently on Jellyfin's version 10.9.11 and i get the same error message when trying to login with telegram. Help would be much apreciated. 
 
I was banging my head against the keyboard thinking i was alone lol. 

By the way, thanks for the awesome plugin hexxone!

**Comment by Borgsareus** [comment]
Hi there @hexxone,

I think i've managed to solve the issue.
I have the login fully functional on 10.9.11! All i had to do was change one line of code and rebuild the project from your source code with that change, and voilà... i now have a working TeleJelly. :)
Can i contribute to your awesome project?
Tks!

**Comment by hexxone** [comment]
> Hi there @hexxone,
> 
> I think i've managed to solve the issue. I have the login fully functional on 10.9.11! All i had to do was change one line of code and rebuild the project from your source code with that change, and voilà... i now have a working TeleJelly. :) Can i contribute to your awesome project? Tks!

Hi there, first of all - sorry for the inconvenience ^^ and thanks for taking the time to come up with a solution!
Unfortunately, I have not been able to find the time to do so. 
So yes, please feel free to open a PR for the fix. It would be much appreciated 👍 
Cheers

**Comment by RevolDark** [comment]
Hello @hexxone ,

I saw that there was a reference that no longer existed in the code, but I was thinking of investigating it like @Borgsareus  did, though I didn’t have the time. Where can I get that awesome code?

Thanks! :)

**Comment by hexxone** [comment]
Hey there, I finally found some time to fix the issue. There is a new release available. 
Unfortunately I made a little mistake and the old release is no longer available in the manifest and can only be installed manually.

Let me know if it works for you or if you encounter any further issues.

**Comment by Borgsareus** [comment]
Sorry for the late reply @hexxone ! Thanks for the new release, i've already installed via repo and i'll restart Jelly to check if it still works with my current setup :) 

Again, tks for the time you've invested on the plugin, i've used it for testing and it's working fine with a little change in TelegramHelper.cs:

        var authRequest = new AuthenticationRequest
        {
            App = Constants.PluginName,
            AppVersion = GetType().Assembly.GetName().Version?.ToString() ?? "0.0.0.1",
            DeviceId = request.Headers[HeaderNames.UserAgent].ToString(),
            DeviceName = "TelegramBrowserSSO",
           // RemoteEndPoint = request.HttpContext.GetNormalizedRemoteIp().ToString(), Changed by me! BCK comment
            RemoteEndPoint = request.HttpContext.Connection.RemoteIpAddress.ToString(),
            UserId = user.Id,
            Username = user.Username
        };

Apparently the request worked with the method above because the one you used was deprecated (i guess). which sounds odd because it should work (i found an MS article with that info for early versions of .NET).

By the way i'm not a dev, i'm driven by curiosity! 👍

**Comment by hexxone** [comment]
Yeah, actually the method has been renamed from `HttpContext.GetNormalizedRemoteIp()` to `HttpContext.GetNormalizedRemoteIP()`. With only the "P" changed to uppercase. This was the only real change required besides changing the targetAbi and updating the packages.

And thanks, glad you like the project :) Enjoy

**Comment by RevolDark** [comment]
Hey friend, I took some time to respond because I've been testing it more thoroughly, and it works well. I've been trying it with already created users, and you just need to assign them to the whitelist of your program and make sure the Telegram alias matches the Jellyfin user.

It works great, and it has a lot of potential. I hope you continue with the project if you have time in the future, of course. :)

Thankss <3
